export const ALERTS_ADD = 'ALERTS_ADD'
export const ALERTS_REMOVE = 'ALERTS_REMOVE'
export const ALERTS_CLOSE = 'ALERTS_CLOSE'
export const ALERTS_CLEAN = 'ALERTS_CLEAN'

export const CLIENTS_REQUEST = 'CLIENTS_REQUEST'
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS'
export const CLIENTS_FAILURE = 'CLIENTS_FAILURE'
