export const ALERTS_ADD = 'ALERTS_ADD'
export const ALERTS_REMOVE = 'ALERTS_REMOVE'
export const ALERTS_CLOSE = 'ALERTS_CLOSE'
export const ALERTS_CLEAN = 'ALERTS_CLEAN'

export const FETCHING_START = 'FETCHING_START'
export const FETCHING_STOP = 'FETCHING_STOP'

export const CLIENTS_SET = 'CLIENTS_SET'
